# Generated by Django 5.2.7 on 2025-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('countries', models.JSONField()),
                ('languages', models.JSONField()),
                ('budget_max', models.FloatField()),
                ('gpa', models.FloatField()),
                ('sat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('gpa_min', models.FloatField()),
                ('sat_min', models.IntegerField()),
                ('international_cost_max', models.FloatField()),
            ],
        ),
    ]
